l10n-argentina:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: Odoo modules for argentina
  psc: local-argentina-maintainers
  psc_rep: local-argentina-maintainers-psc-representative
l10n-austria:
  branches:
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "10.0"
  name: Odoo austria localization
  psc: local-austria-maintainers
  psc_rep: local-austria-maintainers-psc-representative
l10n-belarus:
  branches:
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: L10n Belarus
  psc: local-belarus-maintainers
  psc_rep: local-belarus-maintainers-psc-representative
l10n-belgium:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: L10n Belgium
  psc: local-belgium-maintainers
  psc_rep: local-belgium-maintainers-psc-representative
l10n-brazil:
  branches:
    - "6.0"
    - "6.1"
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: "Localiza\xE7\xE3o brasileira oficial do odoo."
  psc: local-brazil-maintainers
  psc_rep: local-brazil-maintainers-psc-representative
l10n-bulgaria:
  branches:
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: Odoo bulgarian localization
  psc: local-bulgaria-maintainers
  psc_rep: local-bulgaria-maintainers-psc-representative
l10n-cambodia:
  branches:
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: Odoo cambodian localization
  psc: local-cambodia-maintainers
  psc_rep: local-cambodia-maintainers-psc-representative
l10n-canada:
  branches:
    - "6.1"
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo modules for canada
  psc: local-canada-maintainers
  psc_rep: local-canada-maintainers-psc-representative
l10n-chile:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "12.0"
  name: Odoo chilean localization
  psc: local-chile-maintainers
  psc_rep: local-chile-maintainers-psc-representative
l10n-china:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "12.0"
  name: Chinese localization of odoo
  psc: local-china-maintainers
  psc_rep: local-china-maintainers-psc-representative
l10n-colombia:
  branches:
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo modules for colombia
  psc: local-colombia-maintainers
  psc_rep: local-colombia-maintainers-psc-representative
l10n-costa-rica:
  branches:
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "12.0"
  name: Odoo modules for costa Rica
  psc: local-costa-rica-maintainers
  psc_rep: local-costa-rica-maintainers-psc-representative
l10n-croatia:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: Odoo croatian localization
  psc: local-croatia-maintainers
  psc_rep: local-croatia-maintainers-psc-representative
l10n-ecuador:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "17.0"
  name: Odoo localization for ecuador
  psc: local-ecuador-maintainers
  psc_rep: local-ecuador-maintainers-psc-representative
l10n-estonia:
  branches:
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: L10n Estonia
  psc: local-estonia-maintainers
  psc_rep: local-estonia-maintainers-psc-representative
l10n-ethiopia:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Ethiopian localization project
  psc: local-ethiopia-maintainers
  psc_rep: local-ethiopia-maintainers-psc-representative
l10n-finland:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: L10n Finland
  psc: local-finland-maintainers-project-leader
  psc_rep: local-finland-maintainers-psc-representative
l10n-france:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: France localization for odoo
  psc: local-france-maintainers
  psc_rep: local-france-maintainers-psc-representative
l10n-germany:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: L10n Germany
  psc: local-germany-maintainers-project-leader
  psc_rep: local-germany-maintainers-psc-representative
l10n-greece:
  branches:
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo greek localization
  psc: local-greece-maintainers
  psc_rep: local-greece-maintainers-psc-representative
l10n-india:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo localization for india
  psc: local-india-maintainers
  psc_rep: local-india-maintainers-psc-representative
l10n-indonesia:
  branches:
    - "8.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "8.0"
  name: Indonesian localization project
  psc: local-indonesia-maintainers
  psc_rep: local-indonesia-maintainers-psc-representative
l10n-iran:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "17.0"
  name: Odoo localization for iran
  psc: local-iran-maintainers
  psc_rep: local-iran-maintainers-psc-representative
l10n-ireland:
  branches:
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo localization for ireland
  psc: local-ireland-maintainers
  psc_rep: local-ireland-maintainers-psc-representative
l10n-italy:
  branches:
    - "5.0"
    - "6.0"
    - "6.1"
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: Odoo italian localization
  psc: local-italy-maintainers
  psc_rep: local-italy-maintainers-psc-representative
l10n-japan:
  branches:
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: L10n Japan
  psc: local-japan-maintainers
  psc_rep: local-japan-maintainers-psc-representative
l10n-luxemburg:
  branches:
    - "6.0"
    - "6.1"
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: L10n Luxemburg
  psc: local-luxemburg-maintainers
  psc_rep: local-luxemburg-maintainers-psc-representative
l10n-macedonia:
  branches:
    - "12.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "12.0"
  name: Odoo macedonian localization
  psc: local-macedonia-maintainers
  psc_rep: local-macedonia-maintainers-psc-representative
l10n-mexico:
  branches:
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "13.0"
  name: Mexican localization.
  psc: local-mexico-maintainers
  psc_rep: local-mexico-maintainers-psc-representative
l10n-morocco:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Moroccan localization
  psc: local-morocco-maintainers
  psc_rep: local-morocco-maintainers-psc-representative
l10n-netherlands:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: Odoo dutch localization
  psc: local-netherlands-maintainers
  psc_rep: local-netherlands-maintainers-psc-representative
l10n-norway:
  branches:
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: The norwegian localization for odoo
  psc: local-norway-maintainers
  psc_rep: local-norway-maintainers-psc-representative
l10n-peru:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Peruvian localization
  psc: local-peru-maintainers
  psc_rep: local-peru-maintainers-psc-representative
l10n-poland:
  branches:
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo polish localization
  psc: local-poland-maintainers
  psc_rep: local-poland-maintainers-psc-representative
l10n-portugal:
  branches:
    - "6.1"
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: Odoo portuguese localization
  psc: local-portugal-maintainers
  psc_rep: local-portugal-maintainers-psc-representative
l10n-romania:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "16.0"
  name: Romanian localization for odoo
  psc: local-romania-maintainers
  psc_rep: local-romania-maintainers-psc-representative
l10n-russia:
  branches:
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: L10n Russia
  psc: local-russia-maintainers
  psc_rep: local-russia-maintainers-psc-representative
l10n-slovenia:
  branches:
    - "8.0"
    - "10.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "10.0"
  name: Slovenian localization project
  psc: local-slovenia-maintainers
  psc_rep: local-slovenia-maintainers-psc-representative
l10n-spain:
  branches:
    - "4.2"
    - "5.0"
    - "6.0"
    - "6.1"
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "17.0"
  name: Odoo spain localization
  psc: local-spain-maintainers
  psc_rep: local-spain-maintainers-psc-representative
l10n-switzerland:
  branches:
    - "5.0"
    - "6.0"
    - "6.1"
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: Odoo swiss localization
  psc: local-switzerland-maintainers
  psc_rep: local-switzerland-maintainers-psc-representative
l10n-taiwan:
  branches:
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Taiwanese localization
  psc: board
  psc_rep: board
l10n-thailand:
  branches:
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: Thai localization
  psc: local-thailand-maintainers
  psc_rep: local-thailand-maintainers-psc-representative
l10n-turkey:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Turkish localization project
  psc: local-turkey-maintainers
  psc_rep: local-turkey-maintainers-psc-representative
l10n-ukraine:
  branches:
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "12.0"
  name: Ukrainian localization
  psc: local-ukraine-maintainers
  psc_rep: local-ukraine-maintainers-psc-representative
l10n-united-kingdom:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo localization for united kingdom
  psc: local-uk-maintainers
  psc_rep: board
l10n-uruguay:
  branches:
    - "8.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "12.0"
  name: Odoo localization for uruguay
  psc: local-uruguay-maintainers
  psc_rep: local-uruguay-maintainers-psc-representative
l10n-usa:
  branches:
    - "7.0"
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "14.0"
  name: Us localization of odoo
  psc: local-usa-maintainers
  psc_rep: local-usa-maintainers-psc-representative
l10n-venezuela:
  branches:
    - "8.0"
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: Odoo modules for venezuela
  psc: local-venezuela-maintainers
  psc_rep: local-venezuela-maintainers-psc-representative
l10n-vietnam:
  branches:
    - "9.0"
    - "10.0"
    - "11.0"
    - "12.0"
    - "13.0"
    - "14.0"
    - "15.0"
    - "16.0"
    - "17.0"
    - "18.0"
  category: L10n
  default_branch: "11.0"
  name: L10n Vietnam
  psc: local-vietnam-maintainers
  psc_rep: local-vietnam-maintainers-psc-representative
