product-maintainers:
  members:
    - JordiBForgeFlow
    - legalsylvain
    - HaraldPanten
    - sebalix
  name: Product maintainers
  representatives:
    - gurneyalex
    - rousseldenis
product-maintainers-psc-representative:
  members: []
  name: Product maintainers psc representative
  representatives: []
